services:
  # 
  api-gateway:
    build:
      context: ./services/api-gateway
    depends_on:
      - users
    ports:
    - 9090:9090
    volumes:
    - ./services/api-gateway:/src
    restart: always

  # 
  users:
    build:
      context: .
      dockerfile: ./services/users/Development.dockerfile
    volumes:
    - ./:/src
    # command: ls && cd ~/src/services/users && npm run start:dev
    ports:
      - 5000

  # 
  # library: