services:
  # 
  api-gateway:
    build: services/api-gateway
    depends_on:
      - users
    ports:
    - 9090
    restart: always

  # 
  users:
    build: services/users
    ports:
      - 5000

  # 
  # library: