services:
  # 
  api-gateway:
    build: services/api-gateway
    depends_on:
      - users
    ports:
    - 9090
    volumes:
    - ./services/api-gateway:/src
    restart: always

  # 
  users:
    build: services/users
    volumes:
    - ./services/users:/src
    ports:
      - 5000

  # 
  # library: